apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace.name }}
  name: techtrends
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort:
    {{ if .Values.service.targetport }}
      {{ .Values.service.port }}
    {{ else }}
      {{ .Values.service.targetport }}
    {{ end }}
  selector:
    app: techtrends
  type: {{ .Values.service.type }}