##  Name of the workflow.
name: TechTrends - Package with Docker
## Trigger on every push to the main branch
on:
  push:
    branches: [ main ]
## List the steps to be executed by the workflow
jobs:
  ## Set the name of the job
  dockerhub-package-push:
    ## Run the action on the ubuntu-latest operating system
    runs-on: ubuntu-latest
    ## Define a sequence of steps to be executed 
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            bigandyox/techtrends
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
      
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          ## Context should be set to the project directory
          context: .
          ## Reference the Dockerfile for TechTrends application
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          ## Push the image to DockerHub with the listed tags based on the following events/attributes
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}